USE DB_STARTUP
CREATE TABLE [dbo].[TB_EMPRESA]
(
	ID_EMPRESA			INT PRIMARY KEY NOT NULL,
	CNPJ				NCHAR(14) NOT NULL,
	RZ_SOCIAL			NCHAR(30) NOT NULL,
	NM_FANTASIA			NCHAR(20) NOT NULL
)
CREATE TABLE [dbo].[TB_OPER]
(
	ID_OPERADOR			INT NOT NULL,
	CPF_OPER			NCHAR(11) NOT NULL,
	EMAIL_OPER			NCHAR(50) NOT NULL,
	SENHA_OPER			NCHAR(10) NOT NULL,
	NOME_OPER			NCHAR(30) NOT NULL
)
CREATE TABLE [dbo].[TB_EMPRESA_OPER]
(
	ID_EMPRESA			INT NOT NULL,
	ID_OPERADOR			INT NOT NULL,

	FOREIGN KEY(ID_EMPRESA) REFERENCES dbo.TB_EMPRESA(ID_EMPRESA),
	FOREIGN KEY(ID_OPERADOR) REFERENCES dbo.TB_OPER(ID_OPERADOR)
)
CREATE TABLE [dbo].[TB_SERVICO]
(
	ID_TIPOSERVICO			INT PRIMARY KEY NOT NULL,
	VALOR					MONEY	NULL,
	DESCRICAO				NCHAR(30)  NULL
)
CREATE TABLE [dbo].[TB_MOVIMENTACAO]
(
	ID_MOVIMENTACAO				INT PRIMARY KEY NOT NULL,
	CNPJEMP_CONTRATANTE			NCHAR(14) NOT NULL,
	CNPJEMP_CONTRATADA			NCHAR(14) NOT NULL,
	CPF_OPER					NCHAR(11) NOT NULL,
	ID_TIPOSERVICO				INT NOT NULL,
	STATUS_MOVIMENTO			NCHAR(10) NOT NULL,

	FOREIGN KEY(ID_TIPOSERVICO) REFERENCES dbo.TB_SERVICO(ID_TIPOSERVICO)
)
;