USE DB_STARTUP
CREATE TABLE [dbo].[TB_EMPRESA]
(
	ID_EMPRESA			INT IDENTITY(1,1),
	CNPJ				NCHAR(14) NOT NULL,
	RZ_SOCIAL			NCHAR(30) NOT NULL,
	NM_FANTASIA			NCHAR(20) NOT NULL,

	CONSTRAINT PK_EMPRESA PRIMARY KEY (ID_EMPRESA)
)
CREATE TABLE [dbo].[TB_OPER]
(
	ID_OPERADOR			INT IDENTITY(1,1),
	CPF_OPER			NCHAR(11) NOT NULL,
	EMAIL_OPER			NCHAR(50) NOT NULL,
	SENHA_OPER			NCHAR(10) NOT NULL,
	NOME_OPER			NCHAR(30) NOT NULL,

	CONSTRAINT PK_OPERADOR PRIMARY KEY (ID_OPERADOR)
)
CREATE TABLE [dbo].[TB_EMPRESA_OPER]
(
	ID_EMPRESA			INT NOT NULL,
	ID_OPERADOR			INT NOT NULL,

	CONSTRAINT FK_EMPRESA FOREIGN KEY(ID_EMPRESA) REFERENCES dbo.TB_EMPRESA(ID_EMPRESA),
	CONSTRAINT FK_OPERADOR FOREIGN KEY(ID_OPERADOR) REFERENCES dbo.TB_OPER(ID_OPERADOR)
)
CREATE TABLE [dbo].[TB_SERVICO]
(
	ID_TIPOSERVICO			INT IDENTITY(1,1),
	VALOR					MONEY	NULL,
	DESCRICAO				NCHAR(30)  NULL,

	CONSTRAINT PK_SERVICO PRIMARY KEY (ID_TIPOSERVICO),
)
CREATE TABLE [dbo].[TB_MOVIMENTACAO]
(
	ID_MOVIMENTACAO				INT IDENTITY(1,1),
	CNPJEMP_CONTRATANTE			NCHAR(14) NOT NULL,
	CNPJEMP_CONTRATADA			NCHAR(14) NOT NULL,
	CPF_OPER					NCHAR(11) NOT NULL,
	ID_TIPOSERVICO				INT NOT NULL,
	STATUS_MOVIMENTO			NCHAR(10) NOT NULL,

	CONSTRAINT PK_MOVIMENTACAO PRIMARY KEY (ID_MOVIMENTACAO),
	CONSTRAINT FK_SERVICO FOREIGN KEY(ID_TIPOSERVICO) REFERENCES dbo.TB_SERVICO(ID_TIPOSERVICO)
)
;